

// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!

namespace Rfmk.Resolink.Grpc.Converters;

public static partial class Convert
{

    private static FieldByte ToProto(this ResoniteLink.Field_byte self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_byte ToModel(this FieldByte self) => new()
    {
        ID = self.Id,
        Value = (byte)self.Value,
    };

    private static ArrayByte ToProto(this ResoniteLink.Array_byte self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_byte ToModel(this ArrayByte self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => (byte)v).ToList(),
    };

    private static FieldNullableByte ToProto(this ResoniteLink.Field_Nullable_byte self)
    {
        var result = new FieldNullableByte
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_byte ToModel(this FieldNullableByte self)
    {
        var result = new ResoniteLink.Field_Nullable_byte
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = (byte?)self.Value;
        }
        return result;
    }

    private static FieldUShort ToProto(this ResoniteLink.Field_ushort self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_ushort ToModel(this FieldUShort self) => new()
    {
        ID = self.Id,
        Value = (ushort)self.Value,
    };

    private static ArrayUShort ToProto(this ResoniteLink.Array_ushort self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ushort ToModel(this ArrayUShort self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => (ushort)v).ToList(),
    };

    private static FieldNullableUShort ToProto(this ResoniteLink.Field_Nullable_ushort self)
    {
        var result = new FieldNullableUShort
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ushort ToModel(this FieldNullableUShort self)
    {
        var result = new ResoniteLink.Field_Nullable_ushort
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = (ushort?)self.Value;
        }
        return result;
    }

    private static FieldUInt ToProto(this ResoniteLink.Field_uint self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_uint ToModel(this FieldUInt self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayUInt ToProto(this ResoniteLink.Array_uint self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_uint ToModel(this ArrayUInt self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldNullableUInt ToProto(this ResoniteLink.Field_Nullable_uint self)
    {
        var result = new FieldNullableUInt
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value;
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_uint ToModel(this FieldNullableUInt self)
    {
        var result = new ResoniteLink.Field_Nullable_uint
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value;
        }
        return result;
    }

    private static FieldULong ToProto(this ResoniteLink.Field_ulong self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_ulong ToModel(this FieldULong self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayULong ToProto(this ResoniteLink.Array_ulong self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ulong ToModel(this ArrayULong self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldNullableULong ToProto(this ResoniteLink.Field_Nullable_ulong self)
    {
        var result = new FieldNullableULong
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value;
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ulong ToModel(this FieldNullableULong self)
    {
        var result = new ResoniteLink.Field_Nullable_ulong
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value;
        }
        return result;
    }

    private static FieldSByte ToProto(this ResoniteLink.Field_sbyte self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_sbyte ToModel(this FieldSByte self) => new()
    {
        ID = self.Id,
        Value = (sbyte)self.Value,
    };

    private static ArraySByte ToProto(this ResoniteLink.Array_sbyte self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_sbyte ToModel(this ArraySByte self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => (sbyte)v).ToList(),
    };

    private static FieldNullableSByte ToProto(this ResoniteLink.Field_Nullable_sbyte self)
    {
        var result = new FieldNullableSByte
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_sbyte ToModel(this FieldNullableSByte self)
    {
        var result = new ResoniteLink.Field_Nullable_sbyte
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = (sbyte?)self.Value;
        }
        return result;
    }

    private static FieldShort ToProto(this ResoniteLink.Field_short self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_short ToModel(this FieldShort self) => new()
    {
        ID = self.Id,
        Value = (short)self.Value,
    };

    private static ArrayShort ToProto(this ResoniteLink.Array_short self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_short ToModel(this ArrayShort self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => (short)v).ToList(),
    };

    private static FieldNullableShort ToProto(this ResoniteLink.Field_Nullable_short self)
    {
        var result = new FieldNullableShort
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_short ToModel(this FieldNullableShort self)
    {
        var result = new ResoniteLink.Field_Nullable_short
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = (short?)self.Value;
        }
        return result;
    }

    private static FieldInt ToProto(this ResoniteLink.Field_int self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_int ToModel(this FieldInt self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayInt ToProto(this ResoniteLink.Array_int self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_int ToModel(this ArrayInt self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldNullableInt ToProto(this ResoniteLink.Field_Nullable_int self)
    {
        var result = new FieldNullableInt
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value;
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_int ToModel(this FieldNullableInt self)
    {
        var result = new ResoniteLink.Field_Nullable_int
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value;
        }
        return result;
    }

    private static FieldLong ToProto(this ResoniteLink.Field_long self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_long ToModel(this FieldLong self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayLong ToProto(this ResoniteLink.Array_long self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_long ToModel(this ArrayLong self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldNullableLong ToProto(this ResoniteLink.Field_Nullable_long self)
    {
        var result = new FieldNullableLong
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value;
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_long ToModel(this FieldNullableLong self)
    {
        var result = new ResoniteLink.Field_Nullable_long
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value;
        }
        return result;
    }

    private static FieldFloat ToProto(this ResoniteLink.Field_float self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_float ToModel(this FieldFloat self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayFloat ToProto(this ResoniteLink.Array_float self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_float ToModel(this ArrayFloat self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldNullableFloat ToProto(this ResoniteLink.Field_Nullable_float self)
    {
        var result = new FieldNullableFloat
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value;
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_float ToModel(this FieldNullableFloat self)
    {
        var result = new ResoniteLink.Field_Nullable_float
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value;
        }
        return result;
    }

    private static FieldDouble ToProto(this ResoniteLink.Field_double self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_double ToModel(this FieldDouble self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayDouble ToProto(this ResoniteLink.Array_double self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_double ToModel(this ArrayDouble self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldNullableDouble ToProto(this ResoniteLink.Field_Nullable_double self)
    {
        var result = new FieldNullableDouble
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value;
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_double ToModel(this FieldNullableDouble self)
    {
        var result = new ResoniteLink.Field_Nullable_double
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value;
        }
        return result;
    }

    private static FieldDecimal ToProto(this ResoniteLink.Field_decimal self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_decimal ToModel(this FieldDecimal self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDecimal ToProto(this ResoniteLink.Array_decimal self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_decimal ToModel(this ArrayDecimal self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDecimal ToProto(this ResoniteLink.Field_Nullable_decimal self)
    {
        var result = new FieldNullableDecimal
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_decimal ToModel(this FieldNullableDecimal self)
    {
        var result = new ResoniteLink.Field_Nullable_decimal
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldBool ToProto(this ResoniteLink.Field_bool self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_bool ToModel(this FieldBool self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayBool ToProto(this ResoniteLink.Array_bool self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_bool ToModel(this ArrayBool self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldNullableBool ToProto(this ResoniteLink.Field_Nullable_bool self)
    {
        var result = new FieldNullableBool
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value;
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_bool ToModel(this FieldNullableBool self)
    {
        var result = new ResoniteLink.Field_Nullable_bool
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value;
        }
        return result;
    }

    private static FieldChar ToProto(this ResoniteLink.Field_char self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_char ToModel(this FieldChar self) => new()
    {
        ID = self.Id,
        Value = (char)self.Value,
    };

    private static ArrayChar ToProto(this ResoniteLink.Array_char self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_char ToModel(this ArrayChar self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => (char)v).ToList(),
    };

    private static FieldNullableChar ToProto(this ResoniteLink.Field_Nullable_char self)
    {
        var result = new FieldNullableChar
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_char ToModel(this FieldNullableChar self)
    {
        var result = new ResoniteLink.Field_Nullable_char
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = (char?)self.Value;
        }
        return result;
    }

    private static FieldString ToProto(this ResoniteLink.Field_string self) => new()
    {
        Id = self.ID,
        Value = self.Value,
    };

    private static ResoniteLink.Field_string ToModel(this FieldString self) => new()
    {
        ID = self.Id,
        Value = self.Value,
    };

    private static ArrayString ToProto(this ResoniteLink.Array_string self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_string ToModel(this ArrayString self) => new()
    {
        ID = self.Id,
        Values = self.Values.ToList(),
    };

    private static FieldUri ToProto(this ResoniteLink.Field_Uri self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_Uri ToModel(this FieldUri self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUri ToProto(this ResoniteLink.Array_Uri self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_Uri ToModel(this ArrayUri self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldDateTime ToProto(this ResoniteLink.Field_DateTime self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_DateTime ToModel(this FieldDateTime self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDateTime ToProto(this ResoniteLink.Array_DateTime self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_DateTime ToModel(this ArrayDateTime self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDateTime ToProto(this ResoniteLink.Field_Nullable_DateTime self)
    {
        var result = new FieldNullableDateTime
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_DateTime ToModel(this FieldNullableDateTime self)
    {
        var result = new ResoniteLink.Field_Nullable_DateTime
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldTimeSpan ToProto(this ResoniteLink.Field_TimeSpan self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_TimeSpan ToModel(this FieldTimeSpan self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayTimeSpan ToProto(this ResoniteLink.Array_TimeSpan self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_TimeSpan ToModel(this ArrayTimeSpan self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableTimeSpan ToProto(this ResoniteLink.Field_Nullable_TimeSpan self)
    {
        var result = new FieldNullableTimeSpan
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_TimeSpan ToModel(this FieldNullableTimeSpan self)
    {
        var result = new ResoniteLink.Field_Nullable_TimeSpan
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldColor ToProto(this ResoniteLink.Field_color self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_color ToModel(this FieldColor self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayColor ToProto(this ResoniteLink.Array_color self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_color ToModel(this ArrayColor self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableColor ToProto(this ResoniteLink.Field_Nullable_color self)
    {
        var result = new FieldNullableColor
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_color ToModel(this FieldNullableColor self)
    {
        var result = new ResoniteLink.Field_Nullable_color
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldColorX ToProto(this ResoniteLink.Field_colorX self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_colorX ToModel(this FieldColorX self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayColorX ToProto(this ResoniteLink.Array_colorX self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_colorX ToModel(this ArrayColorX self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableColorX ToProto(this ResoniteLink.Field_Nullable_colorX self)
    {
        var result = new FieldNullableColorX
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_colorX ToModel(this FieldNullableColorX self)
    {
        var result = new ResoniteLink.Field_Nullable_colorX
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldColor32 ToProto(this ResoniteLink.Field_color32 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_color32 ToModel(this FieldColor32 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayColor32 ToProto(this ResoniteLink.Array_color32 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_color32 ToModel(this ArrayColor32 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableColor32 ToProto(this ResoniteLink.Field_Nullable_color32 self)
    {
        var result = new FieldNullableColor32
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_color32 ToModel(this FieldNullableColor32 self)
    {
        var result = new ResoniteLink.Field_Nullable_color32
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldFloat2 ToProto(this ResoniteLink.Field_float2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_float2 ToModel(this FieldFloat2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayFloat2 ToProto(this ResoniteLink.Array_float2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_float2 ToModel(this ArrayFloat2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableFloat2 ToProto(this ResoniteLink.Field_Nullable_float2 self)
    {
        var result = new FieldNullableFloat2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_float2 ToModel(this FieldNullableFloat2 self)
    {
        var result = new ResoniteLink.Field_Nullable_float2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldDouble2 ToProto(this ResoniteLink.Field_double2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_double2 ToModel(this FieldDouble2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDouble2 ToProto(this ResoniteLink.Array_double2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_double2 ToModel(this ArrayDouble2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDouble2 ToProto(this ResoniteLink.Field_Nullable_double2 self)
    {
        var result = new FieldNullableDouble2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_double2 ToModel(this FieldNullableDouble2 self)
    {
        var result = new ResoniteLink.Field_Nullable_double2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldByte2 ToProto(this ResoniteLink.Field_byte2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_byte2 ToModel(this FieldByte2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayByte2 ToProto(this ResoniteLink.Array_byte2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_byte2 ToModel(this ArrayByte2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableByte2 ToProto(this ResoniteLink.Field_Nullable_byte2 self)
    {
        var result = new FieldNullableByte2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_byte2 ToModel(this FieldNullableByte2 self)
    {
        var result = new ResoniteLink.Field_Nullable_byte2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUshort2 ToProto(this ResoniteLink.Field_ushort2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_ushort2 ToModel(this FieldUshort2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUshort2 ToProto(this ResoniteLink.Array_ushort2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ushort2 ToModel(this ArrayUshort2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUshort2 ToProto(this ResoniteLink.Field_Nullable_ushort2 self)
    {
        var result = new FieldNullableUshort2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ushort2 ToModel(this FieldNullableUshort2 self)
    {
        var result = new ResoniteLink.Field_Nullable_ushort2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUint2 ToProto(this ResoniteLink.Field_uint2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_uint2 ToModel(this FieldUint2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUint2 ToProto(this ResoniteLink.Array_uint2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_uint2 ToModel(this ArrayUint2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUint2 ToProto(this ResoniteLink.Field_Nullable_uint2 self)
    {
        var result = new FieldNullableUint2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_uint2 ToModel(this FieldNullableUint2 self)
    {
        var result = new ResoniteLink.Field_Nullable_uint2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUlong2 ToProto(this ResoniteLink.Field_ulong2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_ulong2 ToModel(this FieldUlong2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUlong2 ToProto(this ResoniteLink.Array_ulong2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ulong2 ToModel(this ArrayUlong2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUlong2 ToProto(this ResoniteLink.Field_Nullable_ulong2 self)
    {
        var result = new FieldNullableUlong2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ulong2 ToModel(this FieldNullableUlong2 self)
    {
        var result = new ResoniteLink.Field_Nullable_ulong2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldSbyte2 ToProto(this ResoniteLink.Field_sbyte2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_sbyte2 ToModel(this FieldSbyte2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArraySbyte2 ToProto(this ResoniteLink.Array_sbyte2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_sbyte2 ToModel(this ArraySbyte2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableSbyte2 ToProto(this ResoniteLink.Field_Nullable_sbyte2 self)
    {
        var result = new FieldNullableSbyte2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_sbyte2 ToModel(this FieldNullableSbyte2 self)
    {
        var result = new ResoniteLink.Field_Nullable_sbyte2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldShort2 ToProto(this ResoniteLink.Field_short2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_short2 ToModel(this FieldShort2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayShort2 ToProto(this ResoniteLink.Array_short2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_short2 ToModel(this ArrayShort2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableShort2 ToProto(this ResoniteLink.Field_Nullable_short2 self)
    {
        var result = new FieldNullableShort2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_short2 ToModel(this FieldNullableShort2 self)
    {
        var result = new ResoniteLink.Field_Nullable_short2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldInt2 ToProto(this ResoniteLink.Field_int2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_int2 ToModel(this FieldInt2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayInt2 ToProto(this ResoniteLink.Array_int2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_int2 ToModel(this ArrayInt2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableInt2 ToProto(this ResoniteLink.Field_Nullable_int2 self)
    {
        var result = new FieldNullableInt2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_int2 ToModel(this FieldNullableInt2 self)
    {
        var result = new ResoniteLink.Field_Nullable_int2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldLong2 ToProto(this ResoniteLink.Field_long2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_long2 ToModel(this FieldLong2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayLong2 ToProto(this ResoniteLink.Array_long2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_long2 ToModel(this ArrayLong2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableLong2 ToProto(this ResoniteLink.Field_Nullable_long2 self)
    {
        var result = new FieldNullableLong2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_long2 ToModel(this FieldNullableLong2 self)
    {
        var result = new ResoniteLink.Field_Nullable_long2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldBool2 ToProto(this ResoniteLink.Field_bool2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_bool2 ToModel(this FieldBool2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayBool2 ToProto(this ResoniteLink.Array_bool2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_bool2 ToModel(this ArrayBool2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableBool2 ToProto(this ResoniteLink.Field_Nullable_bool2 self)
    {
        var result = new FieldNullableBool2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_bool2 ToModel(this FieldNullableBool2 self)
    {
        var result = new ResoniteLink.Field_Nullable_bool2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldFloat3 ToProto(this ResoniteLink.Field_float3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_float3 ToModel(this FieldFloat3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayFloat3 ToProto(this ResoniteLink.Array_float3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_float3 ToModel(this ArrayFloat3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableFloat3 ToProto(this ResoniteLink.Field_Nullable_float3 self)
    {
        var result = new FieldNullableFloat3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_float3 ToModel(this FieldNullableFloat3 self)
    {
        var result = new ResoniteLink.Field_Nullable_float3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldDouble3 ToProto(this ResoniteLink.Field_double3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_double3 ToModel(this FieldDouble3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDouble3 ToProto(this ResoniteLink.Array_double3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_double3 ToModel(this ArrayDouble3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDouble3 ToProto(this ResoniteLink.Field_Nullable_double3 self)
    {
        var result = new FieldNullableDouble3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_double3 ToModel(this FieldNullableDouble3 self)
    {
        var result = new ResoniteLink.Field_Nullable_double3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldByte3 ToProto(this ResoniteLink.Field_byte3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_byte3 ToModel(this FieldByte3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayByte3 ToProto(this ResoniteLink.Array_byte3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_byte3 ToModel(this ArrayByte3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableByte3 ToProto(this ResoniteLink.Field_Nullable_byte3 self)
    {
        var result = new FieldNullableByte3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_byte3 ToModel(this FieldNullableByte3 self)
    {
        var result = new ResoniteLink.Field_Nullable_byte3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUshort3 ToProto(this ResoniteLink.Field_ushort3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_ushort3 ToModel(this FieldUshort3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUshort3 ToProto(this ResoniteLink.Array_ushort3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ushort3 ToModel(this ArrayUshort3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUshort3 ToProto(this ResoniteLink.Field_Nullable_ushort3 self)
    {
        var result = new FieldNullableUshort3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ushort3 ToModel(this FieldNullableUshort3 self)
    {
        var result = new ResoniteLink.Field_Nullable_ushort3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUint3 ToProto(this ResoniteLink.Field_uint3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_uint3 ToModel(this FieldUint3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUint3 ToProto(this ResoniteLink.Array_uint3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_uint3 ToModel(this ArrayUint3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUint3 ToProto(this ResoniteLink.Field_Nullable_uint3 self)
    {
        var result = new FieldNullableUint3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_uint3 ToModel(this FieldNullableUint3 self)
    {
        var result = new ResoniteLink.Field_Nullable_uint3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUlong3 ToProto(this ResoniteLink.Field_ulong3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_ulong3 ToModel(this FieldUlong3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUlong3 ToProto(this ResoniteLink.Array_ulong3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ulong3 ToModel(this ArrayUlong3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUlong3 ToProto(this ResoniteLink.Field_Nullable_ulong3 self)
    {
        var result = new FieldNullableUlong3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ulong3 ToModel(this FieldNullableUlong3 self)
    {
        var result = new ResoniteLink.Field_Nullable_ulong3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldSbyte3 ToProto(this ResoniteLink.Field_sbyte3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_sbyte3 ToModel(this FieldSbyte3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArraySbyte3 ToProto(this ResoniteLink.Array_sbyte3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_sbyte3 ToModel(this ArraySbyte3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableSbyte3 ToProto(this ResoniteLink.Field_Nullable_sbyte3 self)
    {
        var result = new FieldNullableSbyte3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_sbyte3 ToModel(this FieldNullableSbyte3 self)
    {
        var result = new ResoniteLink.Field_Nullable_sbyte3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldShort3 ToProto(this ResoniteLink.Field_short3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_short3 ToModel(this FieldShort3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayShort3 ToProto(this ResoniteLink.Array_short3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_short3 ToModel(this ArrayShort3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableShort3 ToProto(this ResoniteLink.Field_Nullable_short3 self)
    {
        var result = new FieldNullableShort3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_short3 ToModel(this FieldNullableShort3 self)
    {
        var result = new ResoniteLink.Field_Nullable_short3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldInt3 ToProto(this ResoniteLink.Field_int3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_int3 ToModel(this FieldInt3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayInt3 ToProto(this ResoniteLink.Array_int3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_int3 ToModel(this ArrayInt3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableInt3 ToProto(this ResoniteLink.Field_Nullable_int3 self)
    {
        var result = new FieldNullableInt3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_int3 ToModel(this FieldNullableInt3 self)
    {
        var result = new ResoniteLink.Field_Nullable_int3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldLong3 ToProto(this ResoniteLink.Field_long3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_long3 ToModel(this FieldLong3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayLong3 ToProto(this ResoniteLink.Array_long3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_long3 ToModel(this ArrayLong3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableLong3 ToProto(this ResoniteLink.Field_Nullable_long3 self)
    {
        var result = new FieldNullableLong3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_long3 ToModel(this FieldNullableLong3 self)
    {
        var result = new ResoniteLink.Field_Nullable_long3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldBool3 ToProto(this ResoniteLink.Field_bool3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_bool3 ToModel(this FieldBool3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayBool3 ToProto(this ResoniteLink.Array_bool3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_bool3 ToModel(this ArrayBool3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableBool3 ToProto(this ResoniteLink.Field_Nullable_bool3 self)
    {
        var result = new FieldNullableBool3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_bool3 ToModel(this FieldNullableBool3 self)
    {
        var result = new ResoniteLink.Field_Nullable_bool3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldFloat4 ToProto(this ResoniteLink.Field_float4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_float4 ToModel(this FieldFloat4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayFloat4 ToProto(this ResoniteLink.Array_float4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_float4 ToModel(this ArrayFloat4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableFloat4 ToProto(this ResoniteLink.Field_Nullable_float4 self)
    {
        var result = new FieldNullableFloat4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_float4 ToModel(this FieldNullableFloat4 self)
    {
        var result = new ResoniteLink.Field_Nullable_float4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldDouble4 ToProto(this ResoniteLink.Field_double4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_double4 ToModel(this FieldDouble4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDouble4 ToProto(this ResoniteLink.Array_double4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_double4 ToModel(this ArrayDouble4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDouble4 ToProto(this ResoniteLink.Field_Nullable_double4 self)
    {
        var result = new FieldNullableDouble4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_double4 ToModel(this FieldNullableDouble4 self)
    {
        var result = new ResoniteLink.Field_Nullable_double4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldByte4 ToProto(this ResoniteLink.Field_byte4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_byte4 ToModel(this FieldByte4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayByte4 ToProto(this ResoniteLink.Array_byte4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_byte4 ToModel(this ArrayByte4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableByte4 ToProto(this ResoniteLink.Field_Nullable_byte4 self)
    {
        var result = new FieldNullableByte4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_byte4 ToModel(this FieldNullableByte4 self)
    {
        var result = new ResoniteLink.Field_Nullable_byte4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUshort4 ToProto(this ResoniteLink.Field_ushort4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_ushort4 ToModel(this FieldUshort4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUshort4 ToProto(this ResoniteLink.Array_ushort4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ushort4 ToModel(this ArrayUshort4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUshort4 ToProto(this ResoniteLink.Field_Nullable_ushort4 self)
    {
        var result = new FieldNullableUshort4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ushort4 ToModel(this FieldNullableUshort4 self)
    {
        var result = new ResoniteLink.Field_Nullable_ushort4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUint4 ToProto(this ResoniteLink.Field_uint4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_uint4 ToModel(this FieldUint4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUint4 ToProto(this ResoniteLink.Array_uint4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_uint4 ToModel(this ArrayUint4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUint4 ToProto(this ResoniteLink.Field_Nullable_uint4 self)
    {
        var result = new FieldNullableUint4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_uint4 ToModel(this FieldNullableUint4 self)
    {
        var result = new ResoniteLink.Field_Nullable_uint4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldUlong4 ToProto(this ResoniteLink.Field_ulong4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_ulong4 ToModel(this FieldUlong4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayUlong4 ToProto(this ResoniteLink.Array_ulong4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_ulong4 ToModel(this ArrayUlong4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableUlong4 ToProto(this ResoniteLink.Field_Nullable_ulong4 self)
    {
        var result = new FieldNullableUlong4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_ulong4 ToModel(this FieldNullableUlong4 self)
    {
        var result = new ResoniteLink.Field_Nullable_ulong4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldSbyte4 ToProto(this ResoniteLink.Field_sbyte4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_sbyte4 ToModel(this FieldSbyte4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArraySbyte4 ToProto(this ResoniteLink.Array_sbyte4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_sbyte4 ToModel(this ArraySbyte4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableSbyte4 ToProto(this ResoniteLink.Field_Nullable_sbyte4 self)
    {
        var result = new FieldNullableSbyte4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_sbyte4 ToModel(this FieldNullableSbyte4 self)
    {
        var result = new ResoniteLink.Field_Nullable_sbyte4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldShort4 ToProto(this ResoniteLink.Field_short4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_short4 ToModel(this FieldShort4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayShort4 ToProto(this ResoniteLink.Array_short4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_short4 ToModel(this ArrayShort4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableShort4 ToProto(this ResoniteLink.Field_Nullable_short4 self)
    {
        var result = new FieldNullableShort4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_short4 ToModel(this FieldNullableShort4 self)
    {
        var result = new ResoniteLink.Field_Nullable_short4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldInt4 ToProto(this ResoniteLink.Field_int4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_int4 ToModel(this FieldInt4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayInt4 ToProto(this ResoniteLink.Array_int4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_int4 ToModel(this ArrayInt4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableInt4 ToProto(this ResoniteLink.Field_Nullable_int4 self)
    {
        var result = new FieldNullableInt4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_int4 ToModel(this FieldNullableInt4 self)
    {
        var result = new ResoniteLink.Field_Nullable_int4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldLong4 ToProto(this ResoniteLink.Field_long4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_long4 ToModel(this FieldLong4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayLong4 ToProto(this ResoniteLink.Array_long4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_long4 ToModel(this ArrayLong4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableLong4 ToProto(this ResoniteLink.Field_Nullable_long4 self)
    {
        var result = new FieldNullableLong4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_long4 ToModel(this FieldNullableLong4 self)
    {
        var result = new ResoniteLink.Field_Nullable_long4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldBool4 ToProto(this ResoniteLink.Field_bool4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_bool4 ToModel(this FieldBool4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayBool4 ToProto(this ResoniteLink.Array_bool4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_bool4 ToModel(this ArrayBool4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableBool4 ToProto(this ResoniteLink.Field_Nullable_bool4 self)
    {
        var result = new FieldNullableBool4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_bool4 ToModel(this FieldNullableBool4 self)
    {
        var result = new ResoniteLink.Field_Nullable_bool4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldFloatQ ToProto(this ResoniteLink.Field_floatQ self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_floatQ ToModel(this FieldFloatQ self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayFloatQ ToProto(this ResoniteLink.Array_floatQ self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_floatQ ToModel(this ArrayFloatQ self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableFloatQ ToProto(this ResoniteLink.Field_Nullable_floatQ self)
    {
        var result = new FieldNullableFloatQ
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_floatQ ToModel(this FieldNullableFloatQ self)
    {
        var result = new ResoniteLink.Field_Nullable_floatQ
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldDoubleQ ToProto(this ResoniteLink.Field_doubleQ self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_doubleQ ToModel(this FieldDoubleQ self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDoubleQ ToProto(this ResoniteLink.Array_doubleQ self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_doubleQ ToModel(this ArrayDoubleQ self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDoubleQ ToProto(this ResoniteLink.Field_Nullable_doubleQ self)
    {
        var result = new FieldNullableDoubleQ
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_doubleQ ToModel(this FieldNullableDoubleQ self)
    {
        var result = new ResoniteLink.Field_Nullable_doubleQ
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldFloat2x2 ToProto(this ResoniteLink.Field_float2x2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_float2x2 ToModel(this FieldFloat2x2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayFloat2x2 ToProto(this ResoniteLink.Array_float2x2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_float2x2 ToModel(this ArrayFloat2x2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableFloat2x2 ToProto(this ResoniteLink.Field_Nullable_float2x2 self)
    {
        var result = new FieldNullableFloat2x2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_float2x2 ToModel(this FieldNullableFloat2x2 self)
    {
        var result = new ResoniteLink.Field_Nullable_float2x2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldDouble2x2 ToProto(this ResoniteLink.Field_double2x2 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_double2x2 ToModel(this FieldDouble2x2 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDouble2x2 ToProto(this ResoniteLink.Array_double2x2 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_double2x2 ToModel(this ArrayDouble2x2 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDouble2x2 ToProto(this ResoniteLink.Field_Nullable_double2x2 self)
    {
        var result = new FieldNullableDouble2x2
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_double2x2 ToModel(this FieldNullableDouble2x2 self)
    {
        var result = new ResoniteLink.Field_Nullable_double2x2
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldFloat3x3 ToProto(this ResoniteLink.Field_float3x3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_float3x3 ToModel(this FieldFloat3x3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayFloat3x3 ToProto(this ResoniteLink.Array_float3x3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_float3x3 ToModel(this ArrayFloat3x3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableFloat3x3 ToProto(this ResoniteLink.Field_Nullable_float3x3 self)
    {
        var result = new FieldNullableFloat3x3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_float3x3 ToModel(this FieldNullableFloat3x3 self)
    {
        var result = new ResoniteLink.Field_Nullable_float3x3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldDouble3x3 ToProto(this ResoniteLink.Field_double3x3 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_double3x3 ToModel(this FieldDouble3x3 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDouble3x3 ToProto(this ResoniteLink.Array_double3x3 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_double3x3 ToModel(this ArrayDouble3x3 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDouble3x3 ToProto(this ResoniteLink.Field_Nullable_double3x3 self)
    {
        var result = new FieldNullableDouble3x3
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_double3x3 ToModel(this FieldNullableDouble3x3 self)
    {
        var result = new ResoniteLink.Field_Nullable_double3x3
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldFloat4x4 ToProto(this ResoniteLink.Field_float4x4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_float4x4 ToModel(this FieldFloat4x4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayFloat4x4 ToProto(this ResoniteLink.Array_float4x4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_float4x4 ToModel(this ArrayFloat4x4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableFloat4x4 ToProto(this ResoniteLink.Field_Nullable_float4x4 self)
    {
        var result = new FieldNullableFloat4x4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_float4x4 ToModel(this FieldNullableFloat4x4 self)
    {
        var result = new ResoniteLink.Field_Nullable_float4x4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }

    private static FieldDouble4x4 ToProto(this ResoniteLink.Field_double4x4 self) => new()
    {
        Id = self.ID,
        Value = self.Value.ToProto(),
    };

    private static ResoniteLink.Field_double4x4 ToModel(this FieldDouble4x4 self) => new()
    {
        ID = self.Id,
        Value = self.Value.ToModel(),
    };

    private static ArrayDouble4x4 ToProto(this ResoniteLink.Array_double4x4 self) => new()
    {
        Id = self.ID,
        Values = { self.Values.Select(v => v.ToProto()) },
    };

    private static ResoniteLink.Array_double4x4 ToModel(this ArrayDouble4x4 self) => new()
    {
        ID = self.Id,
        Values = self.Values.Select(v => v.ToModel()).ToList(),
    };

    private static FieldNullableDouble4x4 ToProto(this ResoniteLink.Field_Nullable_double4x4 self)
    {
        var result = new FieldNullableDouble4x4
        {
            Id = self.ID,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.Value.ToProto();
        }
        return result;
    }

    private static ResoniteLink.Field_Nullable_double4x4 ToModel(this FieldNullableDouble4x4 self)
    {
        var result = new ResoniteLink.Field_Nullable_double4x4
        {
            ID = self.Id,
        };
        if (self.Value != null)
        {
            result.Value = self.Value.ToModel();
        }
        return result;
    }
}
