
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace Rfmk.Resolink.Converters;

internal static class PrimitiveConverters
{
    public static ResoniteLink.Field_byte ToLink(this Resonite.FieldByte self)
    {
        return new ResoniteLink.Field_byte {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte ToProto(this ResoniteLink.Field_byte self)
    {
        return new Resonite.FieldByte {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_byte ToNullLink(this Resonite.FieldByte self)
    {
        return new ResoniteLink.Field_Nullable_byte {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte ToProto(this ResoniteLink.Field_Nullable_byte self)
    {
        var result = new Resonite.FieldByte {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ushort ToLink(this Resonite.FieldUShort self)
    {
        return new ResoniteLink.Field_ushort {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort ToProto(this ResoniteLink.Field_ushort self)
    {
        return new Resonite.FieldUShort {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ushort ToNullLink(this Resonite.FieldUShort self)
    {
        return new ResoniteLink.Field_Nullable_ushort {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort ToProto(this ResoniteLink.Field_Nullable_ushort self)
    {
        var result = new Resonite.FieldUShort {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_uint ToLink(this Resonite.FieldUInt self)
    {
        return new ResoniteLink.Field_uint {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt ToProto(this ResoniteLink.Field_uint self)
    {
        return new Resonite.FieldUInt {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_uint ToNullLink(this Resonite.FieldUInt self)
    {
        return new ResoniteLink.Field_Nullable_uint {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt ToProto(this ResoniteLink.Field_Nullable_uint self)
    {
        var result = new Resonite.FieldUInt {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ulong ToLink(this Resonite.FieldULong self)
    {
        return new ResoniteLink.Field_ulong {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong ToProto(this ResoniteLink.Field_ulong self)
    {
        return new Resonite.FieldULong {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ulong ToNullLink(this Resonite.FieldULong self)
    {
        return new ResoniteLink.Field_Nullable_ulong {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong ToProto(this ResoniteLink.Field_Nullable_ulong self)
    {
        var result = new Resonite.FieldULong {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_sbyte ToLink(this Resonite.FieldSByte self)
    {
        return new ResoniteLink.Field_sbyte {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSByte ToProto(this ResoniteLink.Field_sbyte self)
    {
        return new Resonite.FieldSByte {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_sbyte ToNullLink(this Resonite.FieldSByte self)
    {
        return new ResoniteLink.Field_Nullable_sbyte {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSByte ToProto(this ResoniteLink.Field_Nullable_sbyte self)
    {
        var result = new Resonite.FieldSByte {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_short ToLink(this Resonite.FieldShort self)
    {
        return new ResoniteLink.Field_short {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort ToProto(this ResoniteLink.Field_short self)
    {
        return new Resonite.FieldShort {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_short ToNullLink(this Resonite.FieldShort self)
    {
        return new ResoniteLink.Field_Nullable_short {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort ToProto(this ResoniteLink.Field_Nullable_short self)
    {
        var result = new Resonite.FieldShort {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_int ToLink(this Resonite.FieldInt self)
    {
        return new ResoniteLink.Field_int {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt ToProto(this ResoniteLink.Field_int self)
    {
        return new Resonite.FieldInt {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_int ToNullLink(this Resonite.FieldInt self)
    {
        return new ResoniteLink.Field_Nullable_int {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt ToProto(this ResoniteLink.Field_Nullable_int self)
    {
        var result = new Resonite.FieldInt {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_long ToLink(this Resonite.FieldLong self)
    {
        return new ResoniteLink.Field_long {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong ToProto(this ResoniteLink.Field_long self)
    {
        return new Resonite.FieldLong {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_long ToNullLink(this Resonite.FieldLong self)
    {
        return new ResoniteLink.Field_Nullable_long {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong ToProto(this ResoniteLink.Field_Nullable_long self)
    {
        var result = new Resonite.FieldLong {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_float ToLink(this Resonite.FieldFloat self)
    {
        return new ResoniteLink.Field_float {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat ToProto(this ResoniteLink.Field_float self)
    {
        return new Resonite.FieldFloat {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_float ToNullLink(this Resonite.FieldFloat self)
    {
        return new ResoniteLink.Field_Nullable_float {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat ToProto(this ResoniteLink.Field_Nullable_float self)
    {
        var result = new Resonite.FieldFloat {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_double ToLink(this Resonite.FieldDouble self)
    {
        return new ResoniteLink.Field_double {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble ToProto(this ResoniteLink.Field_double self)
    {
        return new Resonite.FieldDouble {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_double ToNullLink(this Resonite.FieldDouble self)
    {
        return new ResoniteLink.Field_Nullable_double {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble ToProto(this ResoniteLink.Field_Nullable_double self)
    {
        var result = new Resonite.FieldDouble {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_decimal ToLink(this Resonite.FieldDecimal self)
    {
        return new ResoniteLink.Field_decimal {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDecimal ToProto(this ResoniteLink.Field_decimal self)
    {
        return new Resonite.FieldDecimal {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_decimal ToNullLink(this Resonite.FieldDecimal self)
    {
        return new ResoniteLink.Field_Nullable_decimal {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDecimal ToProto(this ResoniteLink.Field_Nullable_decimal self)
    {
        var result = new Resonite.FieldDecimal {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_bool ToLink(this Resonite.FieldBool self)
    {
        return new ResoniteLink.Field_bool {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool ToProto(this ResoniteLink.Field_bool self)
    {
        return new Resonite.FieldBool {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_bool ToNullLink(this Resonite.FieldBool self)
    {
        return new ResoniteLink.Field_Nullable_bool {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool ToProto(this ResoniteLink.Field_Nullable_bool self)
    {
        var result = new Resonite.FieldBool {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_char ToLink(this Resonite.FieldChar self)
    {
        return new ResoniteLink.Field_char {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldChar ToProto(this ResoniteLink.Field_char self)
    {
        return new Resonite.FieldChar {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_char ToNullLink(this Resonite.FieldChar self)
    {
        return new ResoniteLink.Field_Nullable_char {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldChar ToProto(this ResoniteLink.Field_Nullable_char self)
    {
        var result = new Resonite.FieldChar {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_string ToLink(this Resonite.FieldString self)
    {
        return new ResoniteLink.Field_string {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldString ToProto(this ResoniteLink.Field_string self)
    {
        return new Resonite.FieldString {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_color ToLink(this Resonite.FieldColor self)
    {
        return new ResoniteLink.Field_color {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldColor ToProto(this ResoniteLink.Field_color self)
    {
        return new Resonite.FieldColor {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_color ToNullLink(this Resonite.FieldColor self)
    {
        return new ResoniteLink.Field_Nullable_color {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldColor ToProto(this ResoniteLink.Field_Nullable_color self)
    {
        var result = new Resonite.FieldColor {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_colorX ToLink(this Resonite.FieldColorX self)
    {
        return new ResoniteLink.Field_colorX {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldColorX ToProto(this ResoniteLink.Field_colorX self)
    {
        return new Resonite.FieldColorX {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_colorX ToNullLink(this Resonite.FieldColorX self)
    {
        return new ResoniteLink.Field_Nullable_colorX {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldColorX ToProto(this ResoniteLink.Field_Nullable_colorX self)
    {
        var result = new Resonite.FieldColorX {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_color32 ToLink(this Resonite.FieldColor32 self)
    {
        return new ResoniteLink.Field_color32 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldColor32 ToProto(this ResoniteLink.Field_color32 self)
    {
        return new Resonite.FieldColor32 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_color32 ToNullLink(this Resonite.FieldColor32 self)
    {
        return new ResoniteLink.Field_Nullable_color32 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldColor32 ToProto(this ResoniteLink.Field_Nullable_color32 self)
    {
        var result = new Resonite.FieldColor32 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_float2 ToLink(this Resonite.FieldFloat2 self)
    {
        return new ResoniteLink.Field_float2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat2 ToProto(this ResoniteLink.Field_float2 self)
    {
        return new Resonite.FieldFloat2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_float2 ToNullLink(this Resonite.FieldFloat2 self)
    {
        return new ResoniteLink.Field_Nullable_float2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat2 ToProto(this ResoniteLink.Field_Nullable_float2 self)
    {
        var result = new Resonite.FieldFloat2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_double2 ToLink(this Resonite.FieldDouble2 self)
    {
        return new ResoniteLink.Field_double2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble2 ToProto(this ResoniteLink.Field_double2 self)
    {
        return new Resonite.FieldDouble2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_double2 ToNullLink(this Resonite.FieldDouble2 self)
    {
        return new ResoniteLink.Field_Nullable_double2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble2 ToProto(this ResoniteLink.Field_Nullable_double2 self)
    {
        var result = new Resonite.FieldDouble2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_byte2 ToLink(this Resonite.FieldByte2 self)
    {
        return new ResoniteLink.Field_byte2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte2 ToProto(this ResoniteLink.Field_byte2 self)
    {
        return new Resonite.FieldByte2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_byte2 ToNullLink(this Resonite.FieldByte2 self)
    {
        return new ResoniteLink.Field_Nullable_byte2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte2 ToProto(this ResoniteLink.Field_Nullable_byte2 self)
    {
        var result = new Resonite.FieldByte2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ushort2 ToLink(this Resonite.FieldUShort2 self)
    {
        return new ResoniteLink.Field_ushort2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort2 ToProto(this ResoniteLink.Field_ushort2 self)
    {
        return new Resonite.FieldUShort2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ushort2 ToNullLink(this Resonite.FieldUShort2 self)
    {
        return new ResoniteLink.Field_Nullable_ushort2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort2 ToProto(this ResoniteLink.Field_Nullable_ushort2 self)
    {
        var result = new Resonite.FieldUShort2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_uint2 ToLink(this Resonite.FieldUInt2 self)
    {
        return new ResoniteLink.Field_uint2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt2 ToProto(this ResoniteLink.Field_uint2 self)
    {
        return new Resonite.FieldUInt2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_uint2 ToNullLink(this Resonite.FieldUInt2 self)
    {
        return new ResoniteLink.Field_Nullable_uint2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt2 ToProto(this ResoniteLink.Field_Nullable_uint2 self)
    {
        var result = new Resonite.FieldUInt2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ulong2 ToLink(this Resonite.FieldULong2 self)
    {
        return new ResoniteLink.Field_ulong2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong2 ToProto(this ResoniteLink.Field_ulong2 self)
    {
        return new Resonite.FieldULong2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ulong2 ToNullLink(this Resonite.FieldULong2 self)
    {
        return new ResoniteLink.Field_Nullable_ulong2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong2 ToProto(this ResoniteLink.Field_Nullable_ulong2 self)
    {
        var result = new Resonite.FieldULong2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_sbyte2 ToLink(this Resonite.FieldSbyte2 self)
    {
        return new ResoniteLink.Field_sbyte2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSbyte2 ToProto(this ResoniteLink.Field_sbyte2 self)
    {
        return new Resonite.FieldSbyte2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_sbyte2 ToNullLink(this Resonite.FieldSbyte2 self)
    {
        return new ResoniteLink.Field_Nullable_sbyte2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSbyte2 ToProto(this ResoniteLink.Field_Nullable_sbyte2 self)
    {
        var result = new Resonite.FieldSbyte2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_short2 ToLink(this Resonite.FieldShort2 self)
    {
        return new ResoniteLink.Field_short2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort2 ToProto(this ResoniteLink.Field_short2 self)
    {
        return new Resonite.FieldShort2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_short2 ToNullLink(this Resonite.FieldShort2 self)
    {
        return new ResoniteLink.Field_Nullable_short2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort2 ToProto(this ResoniteLink.Field_Nullable_short2 self)
    {
        var result = new Resonite.FieldShort2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_int2 ToLink(this Resonite.FieldInt2 self)
    {
        return new ResoniteLink.Field_int2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt2 ToProto(this ResoniteLink.Field_int2 self)
    {
        return new Resonite.FieldInt2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_int2 ToNullLink(this Resonite.FieldInt2 self)
    {
        return new ResoniteLink.Field_Nullable_int2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt2 ToProto(this ResoniteLink.Field_Nullable_int2 self)
    {
        var result = new Resonite.FieldInt2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_long2 ToLink(this Resonite.FieldLong2 self)
    {
        return new ResoniteLink.Field_long2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong2 ToProto(this ResoniteLink.Field_long2 self)
    {
        return new Resonite.FieldLong2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_long2 ToNullLink(this Resonite.FieldLong2 self)
    {
        return new ResoniteLink.Field_Nullable_long2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong2 ToProto(this ResoniteLink.Field_Nullable_long2 self)
    {
        var result = new Resonite.FieldLong2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_bool2 ToLink(this Resonite.FieldBool2 self)
    {
        return new ResoniteLink.Field_bool2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool2 ToProto(this ResoniteLink.Field_bool2 self)
    {
        return new Resonite.FieldBool2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_bool2 ToNullLink(this Resonite.FieldBool2 self)
    {
        return new ResoniteLink.Field_Nullable_bool2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool2 ToProto(this ResoniteLink.Field_Nullable_bool2 self)
    {
        var result = new Resonite.FieldBool2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_float3 ToLink(this Resonite.FieldFloat3 self)
    {
        return new ResoniteLink.Field_float3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat3 ToProto(this ResoniteLink.Field_float3 self)
    {
        return new Resonite.FieldFloat3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_float3 ToNullLink(this Resonite.FieldFloat3 self)
    {
        return new ResoniteLink.Field_Nullable_float3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat3 ToProto(this ResoniteLink.Field_Nullable_float3 self)
    {
        var result = new Resonite.FieldFloat3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_double3 ToLink(this Resonite.FieldDouble3 self)
    {
        return new ResoniteLink.Field_double3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble3 ToProto(this ResoniteLink.Field_double3 self)
    {
        return new Resonite.FieldDouble3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_double3 ToNullLink(this Resonite.FieldDouble3 self)
    {
        return new ResoniteLink.Field_Nullable_double3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble3 ToProto(this ResoniteLink.Field_Nullable_double3 self)
    {
        var result = new Resonite.FieldDouble3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_byte3 ToLink(this Resonite.FieldByte3 self)
    {
        return new ResoniteLink.Field_byte3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte3 ToProto(this ResoniteLink.Field_byte3 self)
    {
        return new Resonite.FieldByte3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_byte3 ToNullLink(this Resonite.FieldByte3 self)
    {
        return new ResoniteLink.Field_Nullable_byte3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte3 ToProto(this ResoniteLink.Field_Nullable_byte3 self)
    {
        var result = new Resonite.FieldByte3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ushort3 ToLink(this Resonite.FieldUShort3 self)
    {
        return new ResoniteLink.Field_ushort3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort3 ToProto(this ResoniteLink.Field_ushort3 self)
    {
        return new Resonite.FieldUShort3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ushort3 ToNullLink(this Resonite.FieldUShort3 self)
    {
        return new ResoniteLink.Field_Nullable_ushort3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort3 ToProto(this ResoniteLink.Field_Nullable_ushort3 self)
    {
        var result = new Resonite.FieldUShort3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_uint3 ToLink(this Resonite.FieldUInt3 self)
    {
        return new ResoniteLink.Field_uint3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt3 ToProto(this ResoniteLink.Field_uint3 self)
    {
        return new Resonite.FieldUInt3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_uint3 ToNullLink(this Resonite.FieldUInt3 self)
    {
        return new ResoniteLink.Field_Nullable_uint3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt3 ToProto(this ResoniteLink.Field_Nullable_uint3 self)
    {
        var result = new Resonite.FieldUInt3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ulong3 ToLink(this Resonite.FieldULong3 self)
    {
        return new ResoniteLink.Field_ulong3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong3 ToProto(this ResoniteLink.Field_ulong3 self)
    {
        return new Resonite.FieldULong3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ulong3 ToNullLink(this Resonite.FieldULong3 self)
    {
        return new ResoniteLink.Field_Nullable_ulong3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong3 ToProto(this ResoniteLink.Field_Nullable_ulong3 self)
    {
        var result = new Resonite.FieldULong3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_sbyte3 ToLink(this Resonite.FieldSbyte3 self)
    {
        return new ResoniteLink.Field_sbyte3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSbyte3 ToProto(this ResoniteLink.Field_sbyte3 self)
    {
        return new Resonite.FieldSbyte3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_sbyte3 ToNullLink(this Resonite.FieldSbyte3 self)
    {
        return new ResoniteLink.Field_Nullable_sbyte3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSbyte3 ToProto(this ResoniteLink.Field_Nullable_sbyte3 self)
    {
        var result = new Resonite.FieldSbyte3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_short3 ToLink(this Resonite.FieldShort3 self)
    {
        return new ResoniteLink.Field_short3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort3 ToProto(this ResoniteLink.Field_short3 self)
    {
        return new Resonite.FieldShort3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_short3 ToNullLink(this Resonite.FieldShort3 self)
    {
        return new ResoniteLink.Field_Nullable_short3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort3 ToProto(this ResoniteLink.Field_Nullable_short3 self)
    {
        var result = new Resonite.FieldShort3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_int3 ToLink(this Resonite.FieldInt3 self)
    {
        return new ResoniteLink.Field_int3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt3 ToProto(this ResoniteLink.Field_int3 self)
    {
        return new Resonite.FieldInt3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_int3 ToNullLink(this Resonite.FieldInt3 self)
    {
        return new ResoniteLink.Field_Nullable_int3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt3 ToProto(this ResoniteLink.Field_Nullable_int3 self)
    {
        var result = new Resonite.FieldInt3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_long3 ToLink(this Resonite.FieldLong3 self)
    {
        return new ResoniteLink.Field_long3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong3 ToProto(this ResoniteLink.Field_long3 self)
    {
        return new Resonite.FieldLong3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_long3 ToNullLink(this Resonite.FieldLong3 self)
    {
        return new ResoniteLink.Field_Nullable_long3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong3 ToProto(this ResoniteLink.Field_Nullable_long3 self)
    {
        var result = new Resonite.FieldLong3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_bool3 ToLink(this Resonite.FieldBool3 self)
    {
        return new ResoniteLink.Field_bool3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool3 ToProto(this ResoniteLink.Field_bool3 self)
    {
        return new Resonite.FieldBool3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_bool3 ToNullLink(this Resonite.FieldBool3 self)
    {
        return new ResoniteLink.Field_Nullable_bool3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool3 ToProto(this ResoniteLink.Field_Nullable_bool3 self)
    {
        var result = new Resonite.FieldBool3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_float4 ToLink(this Resonite.FieldFloat4 self)
    {
        return new ResoniteLink.Field_float4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat4 ToProto(this ResoniteLink.Field_float4 self)
    {
        return new Resonite.FieldFloat4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_float4 ToNullLink(this Resonite.FieldFloat4 self)
    {
        return new ResoniteLink.Field_Nullable_float4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat4 ToProto(this ResoniteLink.Field_Nullable_float4 self)
    {
        var result = new Resonite.FieldFloat4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_double4 ToLink(this Resonite.FieldDouble4 self)
    {
        return new ResoniteLink.Field_double4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble4 ToProto(this ResoniteLink.Field_double4 self)
    {
        return new Resonite.FieldDouble4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_double4 ToNullLink(this Resonite.FieldDouble4 self)
    {
        return new ResoniteLink.Field_Nullable_double4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble4 ToProto(this ResoniteLink.Field_Nullable_double4 self)
    {
        var result = new Resonite.FieldDouble4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_byte4 ToLink(this Resonite.FieldByte4 self)
    {
        return new ResoniteLink.Field_byte4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte4 ToProto(this ResoniteLink.Field_byte4 self)
    {
        return new Resonite.FieldByte4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_byte4 ToNullLink(this Resonite.FieldByte4 self)
    {
        return new ResoniteLink.Field_Nullable_byte4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldByte4 ToProto(this ResoniteLink.Field_Nullable_byte4 self)
    {
        var result = new Resonite.FieldByte4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ushort4 ToLink(this Resonite.FieldUShort4 self)
    {
        return new ResoniteLink.Field_ushort4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort4 ToProto(this ResoniteLink.Field_ushort4 self)
    {
        return new Resonite.FieldUShort4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ushort4 ToNullLink(this Resonite.FieldUShort4 self)
    {
        return new ResoniteLink.Field_Nullable_ushort4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUShort4 ToProto(this ResoniteLink.Field_Nullable_ushort4 self)
    {
        var result = new Resonite.FieldUShort4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_uint4 ToLink(this Resonite.FieldUInt4 self)
    {
        return new ResoniteLink.Field_uint4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt4 ToProto(this ResoniteLink.Field_uint4 self)
    {
        return new Resonite.FieldUInt4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_uint4 ToNullLink(this Resonite.FieldUInt4 self)
    {
        return new ResoniteLink.Field_Nullable_uint4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldUInt4 ToProto(this ResoniteLink.Field_Nullable_uint4 self)
    {
        var result = new Resonite.FieldUInt4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_ulong4 ToLink(this Resonite.FieldULong4 self)
    {
        return new ResoniteLink.Field_ulong4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong4 ToProto(this ResoniteLink.Field_ulong4 self)
    {
        return new Resonite.FieldULong4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_ulong4 ToNullLink(this Resonite.FieldULong4 self)
    {
        return new ResoniteLink.Field_Nullable_ulong4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldULong4 ToProto(this ResoniteLink.Field_Nullable_ulong4 self)
    {
        var result = new Resonite.FieldULong4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_sbyte4 ToLink(this Resonite.FieldSbyte4 self)
    {
        return new ResoniteLink.Field_sbyte4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSbyte4 ToProto(this ResoniteLink.Field_sbyte4 self)
    {
        return new Resonite.FieldSbyte4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_sbyte4 ToNullLink(this Resonite.FieldSbyte4 self)
    {
        return new ResoniteLink.Field_Nullable_sbyte4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldSbyte4 ToProto(this ResoniteLink.Field_Nullable_sbyte4 self)
    {
        var result = new Resonite.FieldSbyte4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_short4 ToLink(this Resonite.FieldShort4 self)
    {
        return new ResoniteLink.Field_short4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort4 ToProto(this ResoniteLink.Field_short4 self)
    {
        return new Resonite.FieldShort4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_short4 ToNullLink(this Resonite.FieldShort4 self)
    {
        return new ResoniteLink.Field_Nullable_short4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldShort4 ToProto(this ResoniteLink.Field_Nullable_short4 self)
    {
        var result = new Resonite.FieldShort4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_int4 ToLink(this Resonite.FieldInt4 self)
    {
        return new ResoniteLink.Field_int4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt4 ToProto(this ResoniteLink.Field_int4 self)
    {
        return new Resonite.FieldInt4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_int4 ToNullLink(this Resonite.FieldInt4 self)
    {
        return new ResoniteLink.Field_Nullable_int4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldInt4 ToProto(this ResoniteLink.Field_Nullable_int4 self)
    {
        var result = new Resonite.FieldInt4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_long4 ToLink(this Resonite.FieldLong4 self)
    {
        return new ResoniteLink.Field_long4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong4 ToProto(this ResoniteLink.Field_long4 self)
    {
        return new Resonite.FieldLong4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_long4 ToNullLink(this Resonite.FieldLong4 self)
    {
        return new ResoniteLink.Field_Nullable_long4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldLong4 ToProto(this ResoniteLink.Field_Nullable_long4 self)
    {
        var result = new Resonite.FieldLong4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_bool4 ToLink(this Resonite.FieldBool4 self)
    {
        return new ResoniteLink.Field_bool4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool4 ToProto(this ResoniteLink.Field_bool4 self)
    {
        return new Resonite.FieldBool4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_bool4 ToNullLink(this Resonite.FieldBool4 self)
    {
        return new ResoniteLink.Field_Nullable_bool4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldBool4 ToProto(this ResoniteLink.Field_Nullable_bool4 self)
    {
        var result = new Resonite.FieldBool4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_floatQ ToLink(this Resonite.FieldFloatQ self)
    {
        return new ResoniteLink.Field_floatQ {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloatQ ToProto(this ResoniteLink.Field_floatQ self)
    {
        return new Resonite.FieldFloatQ {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_floatQ ToNullLink(this Resonite.FieldFloatQ self)
    {
        return new ResoniteLink.Field_Nullable_floatQ {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloatQ ToProto(this ResoniteLink.Field_Nullable_floatQ self)
    {
        var result = new Resonite.FieldFloatQ {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_doubleQ ToLink(this Resonite.FieldDoubleQ self)
    {
        return new ResoniteLink.Field_doubleQ {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDoubleQ ToProto(this ResoniteLink.Field_doubleQ self)
    {
        return new Resonite.FieldDoubleQ {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_doubleQ ToNullLink(this Resonite.FieldDoubleQ self)
    {
        return new ResoniteLink.Field_Nullable_doubleQ {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDoubleQ ToProto(this ResoniteLink.Field_Nullable_doubleQ self)
    {
        var result = new Resonite.FieldDoubleQ {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_float2x2 ToLink(this Resonite.FieldFloat2x2 self)
    {
        return new ResoniteLink.Field_float2x2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat2x2 ToProto(this ResoniteLink.Field_float2x2 self)
    {
        return new Resonite.FieldFloat2x2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_float2x2 ToNullLink(this Resonite.FieldFloat2x2 self)
    {
        return new ResoniteLink.Field_Nullable_float2x2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat2x2 ToProto(this ResoniteLink.Field_Nullable_float2x2 self)
    {
        var result = new Resonite.FieldFloat2x2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_double2x2 ToLink(this Resonite.FieldDouble2x2 self)
    {
        return new ResoniteLink.Field_double2x2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble2x2 ToProto(this ResoniteLink.Field_double2x2 self)
    {
        return new Resonite.FieldDouble2x2 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_double2x2 ToNullLink(this Resonite.FieldDouble2x2 self)
    {
        return new ResoniteLink.Field_Nullable_double2x2 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble2x2 ToProto(this ResoniteLink.Field_Nullable_double2x2 self)
    {
        var result = new Resonite.FieldDouble2x2 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_float3x3 ToLink(this Resonite.FieldFloat3x3 self)
    {
        return new ResoniteLink.Field_float3x3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat3x3 ToProto(this ResoniteLink.Field_float3x3 self)
    {
        return new Resonite.FieldFloat3x3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_float3x3 ToNullLink(this Resonite.FieldFloat3x3 self)
    {
        return new ResoniteLink.Field_Nullable_float3x3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat3x3 ToProto(this ResoniteLink.Field_Nullable_float3x3 self)
    {
        var result = new Resonite.FieldFloat3x3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_double3x3 ToLink(this Resonite.FieldDouble3x3 self)
    {
        return new ResoniteLink.Field_double3x3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble3x3 ToProto(this ResoniteLink.Field_double3x3 self)
    {
        return new Resonite.FieldDouble3x3 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_double3x3 ToNullLink(this Resonite.FieldDouble3x3 self)
    {
        return new ResoniteLink.Field_Nullable_double3x3 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble3x3 ToProto(this ResoniteLink.Field_Nullable_double3x3 self)
    {
        var result = new Resonite.FieldDouble3x3 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_float4x4 ToLink(this Resonite.FieldFloat4x4 self)
    {
        return new ResoniteLink.Field_float4x4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat4x4 ToProto(this ResoniteLink.Field_float4x4 self)
    {
        return new Resonite.FieldFloat4x4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_float4x4 ToNullLink(this Resonite.FieldFloat4x4 self)
    {
        return new ResoniteLink.Field_Nullable_float4x4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldFloat4x4 ToProto(this ResoniteLink.Field_Nullable_float4x4 self)
    {
        var result = new Resonite.FieldFloat4x4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

        public static ResoniteLink.Field_double4x4 ToLink(this Resonite.FieldDouble4x4 self)
    {
        return new ResoniteLink.Field_double4x4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble4x4 ToProto(this ResoniteLink.Field_double4x4 self)
    {
        return new Resonite.FieldDouble4x4 {
          Id = self.ID,
          Value = self.Value,
        };
    }

        public static ResoniteLink.Field_Nullable_double4x4 ToNullLink(this Resonite.FieldDouble4x4 self)
    {
        return new ResoniteLink.Field_Nullable_double4x4 {
          ID = self.Id,
          Value = self.Value,
        };
    }

    public static Resonite.FieldDouble4x4 ToProto(this ResoniteLink.Field_Nullable_double4x4 self)
    {
        var result = new Resonite.FieldDouble4x4 {
          Id = self.ID,
        };
        if (self.Value != null) {
          result.Value = self.Value ?? default;
        }
        return result;
    }

    }