

// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!

namespace Rfmk.Resolink.Grpc.Converters;

public static partial class Convert
{

    private static FloatQ ToProto(this ResoniteLink.floatQ self)
    {
        return new FloatQ
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.floatQ ToModel(this FloatQ self)
    {
        return new ResoniteLink.floatQ
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static DoubleQ ToProto(this ResoniteLink.doubleQ self)
    {
        return new DoubleQ
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.doubleQ ToModel(this DoubleQ self)
    {
        return new ResoniteLink.doubleQ
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Float2 ToProto(this ResoniteLink.float2 self)
    {
        return new Float2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.float2 ToModel(this Float2 self)
    {
        return new ResoniteLink.float2
        {
            x = self.X,
            y = self.Y,
        };
    }

    private static Float3 ToProto(this ResoniteLink.float3 self)
    {
        return new Float3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.float3 ToModel(this Float3 self)
    {
        return new ResoniteLink.float3
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
        };
    }

    private static Float4 ToProto(this ResoniteLink.float4 self)
    {
        return new Float4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.float4 ToModel(this Float4 self)
    {
        return new ResoniteLink.float4
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Double2 ToProto(this ResoniteLink.double2 self)
    {
        return new Double2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.double2 ToModel(this Double2 self)
    {
        return new ResoniteLink.double2
        {
            x = self.X,
            y = self.Y,
        };
    }

    private static Double3 ToProto(this ResoniteLink.double3 self)
    {
        return new Double3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.double3 ToModel(this Double3 self)
    {
        return new ResoniteLink.double3
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
        };
    }

    private static Double4 ToProto(this ResoniteLink.double4 self)
    {
        return new Double4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.double4 ToModel(this Double4 self)
    {
        return new ResoniteLink.double4
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Byte2 ToProto(this ResoniteLink.byte2 self)
    {
        return new Byte2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.byte2 ToModel(this Byte2 self)
    {
        return new ResoniteLink.byte2
        {
            x = (byte)self.X,
            y = (byte)self.Y,
        };
    }

    private static Byte3 ToProto(this ResoniteLink.byte3 self)
    {
        return new Byte3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.byte3 ToModel(this Byte3 self)
    {
        return new ResoniteLink.byte3
        {
            x = (byte)self.X,
            y = (byte)self.Y,
            z = (byte)self.Z,
        };
    }

    private static Byte4 ToProto(this ResoniteLink.byte4 self)
    {
        return new Byte4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.byte4 ToModel(this Byte4 self)
    {
        return new ResoniteLink.byte4
        {
            x = (byte)self.X,
            y = (byte)self.Y,
            z = (byte)self.Z,
            w = (byte)self.W,
        };
    }

    private static Ushort2 ToProto(this ResoniteLink.ushort2 self)
    {
        return new Ushort2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.ushort2 ToModel(this Ushort2 self)
    {
        return new ResoniteLink.ushort2
        {
            x = (ushort)self.X,
            y = (ushort)self.Y,
        };
    }

    private static Ushort3 ToProto(this ResoniteLink.ushort3 self)
    {
        return new Ushort3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.ushort3 ToModel(this Ushort3 self)
    {
        return new ResoniteLink.ushort3
        {
            x = (ushort)self.X,
            y = (ushort)self.Y,
            z = (ushort)self.Z,
        };
    }

    private static Ushort4 ToProto(this ResoniteLink.ushort4 self)
    {
        return new Ushort4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.ushort4 ToModel(this Ushort4 self)
    {
        return new ResoniteLink.ushort4
        {
            x = (ushort)self.X,
            y = (ushort)self.Y,
            z = (ushort)self.Z,
            w = (ushort)self.W,
        };
    }

    private static Uint2 ToProto(this ResoniteLink.uint2 self)
    {
        return new Uint2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.uint2 ToModel(this Uint2 self)
    {
        return new ResoniteLink.uint2
        {
            x = self.X,
            y = self.Y,
        };
    }

    private static Uint3 ToProto(this ResoniteLink.uint3 self)
    {
        return new Uint3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.uint3 ToModel(this Uint3 self)
    {
        return new ResoniteLink.uint3
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
        };
    }

    private static Uint4 ToProto(this ResoniteLink.uint4 self)
    {
        return new Uint4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.uint4 ToModel(this Uint4 self)
    {
        return new ResoniteLink.uint4
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Ulong2 ToProto(this ResoniteLink.ulong2 self)
    {
        return new Ulong2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.ulong2 ToModel(this Ulong2 self)
    {
        return new ResoniteLink.ulong2
        {
            x = self.X,
            y = self.Y,
        };
    }

    private static Ulong3 ToProto(this ResoniteLink.ulong3 self)
    {
        return new Ulong3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.ulong3 ToModel(this Ulong3 self)
    {
        return new ResoniteLink.ulong3
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
        };
    }

    private static Ulong4 ToProto(this ResoniteLink.ulong4 self)
    {
        return new Ulong4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.ulong4 ToModel(this Ulong4 self)
    {
        return new ResoniteLink.ulong4
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Sbyte2 ToProto(this ResoniteLink.sbyte2 self)
    {
        return new Sbyte2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.sbyte2 ToModel(this Sbyte2 self)
    {
        return new ResoniteLink.sbyte2
        {
            x = (sbyte)self.X,
            y = (sbyte)self.Y,
        };
    }

    private static Sbyte3 ToProto(this ResoniteLink.sbyte3 self)
    {
        return new Sbyte3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.sbyte3 ToModel(this Sbyte3 self)
    {
        return new ResoniteLink.sbyte3
        {
            x = (sbyte)self.X,
            y = (sbyte)self.Y,
            z = (sbyte)self.Z,
        };
    }

    private static Sbyte4 ToProto(this ResoniteLink.sbyte4 self)
    {
        return new Sbyte4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.sbyte4 ToModel(this Sbyte4 self)
    {
        return new ResoniteLink.sbyte4
        {
            x = (sbyte)self.X,
            y = (sbyte)self.Y,
            z = (sbyte)self.Z,
            w = (sbyte)self.W,
        };
    }

    private static Short2 ToProto(this ResoniteLink.short2 self)
    {
        return new Short2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.short2 ToModel(this Short2 self)
    {
        return new ResoniteLink.short2
        {
            x = (short)self.X,
            y = (short)self.Y,
        };
    }

    private static Short3 ToProto(this ResoniteLink.short3 self)
    {
        return new Short3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.short3 ToModel(this Short3 self)
    {
        return new ResoniteLink.short3
        {
            x = (short)self.X,
            y = (short)self.Y,
            z = (short)self.Z,
        };
    }

    private static Short4 ToProto(this ResoniteLink.short4 self)
    {
        return new Short4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.short4 ToModel(this Short4 self)
    {
        return new ResoniteLink.short4
        {
            x = (short)self.X,
            y = (short)self.Y,
            z = (short)self.Z,
            w = (short)self.W,
        };
    }

    private static Int2 ToProto(this ResoniteLink.int2 self)
    {
        return new Int2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.int2 ToModel(this Int2 self)
    {
        return new ResoniteLink.int2
        {
            x = self.X,
            y = self.Y,
        };
    }

    private static Int3 ToProto(this ResoniteLink.int3 self)
    {
        return new Int3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.int3 ToModel(this Int3 self)
    {
        return new ResoniteLink.int3
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
        };
    }

    private static Int4 ToProto(this ResoniteLink.int4 self)
    {
        return new Int4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.int4 ToModel(this Int4 self)
    {
        return new ResoniteLink.int4
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Long2 ToProto(this ResoniteLink.long2 self)
    {
        return new Long2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.long2 ToModel(this Long2 self)
    {
        return new ResoniteLink.long2
        {
            x = self.X,
            y = self.Y,
        };
    }

    private static Long3 ToProto(this ResoniteLink.long3 self)
    {
        return new Long3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.long3 ToModel(this Long3 self)
    {
        return new ResoniteLink.long3
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
        };
    }

    private static Long4 ToProto(this ResoniteLink.long4 self)
    {
        return new Long4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.long4 ToModel(this Long4 self)
    {
        return new ResoniteLink.long4
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Bool2 ToProto(this ResoniteLink.bool2 self)
    {
        return new Bool2
        {
            X = self.x,
            Y = self.y,
        };
    }

    private static ResoniteLink.bool2 ToModel(this Bool2 self)
    {
        return new ResoniteLink.bool2
        {
            x = self.X,
            y = self.Y,
        };
    }

    private static Bool3 ToProto(this ResoniteLink.bool3 self)
    {
        return new Bool3
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
        };
    }

    private static ResoniteLink.bool3 ToModel(this Bool3 self)
    {
        return new ResoniteLink.bool3
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
        };
    }

    private static Bool4 ToProto(this ResoniteLink.bool4 self)
    {
        return new Bool4
        {
            X = self.x,
            Y = self.y,
            Z = self.z,
            W = self.w,
        };
    }

    private static ResoniteLink.bool4 ToModel(this Bool4 self)
    {
        return new ResoniteLink.bool4
        {
            x = self.X,
            y = self.Y,
            z = self.Z,
            w = self.W,
        };
    }

    private static Float2x2 ToProto(this ResoniteLink.float2x2 self)
    {
        return new Float2x2
        {
            M00 = self.m00,
            M01 = self.m01,
            M10 = self.m10,
            M11 = self.m11,
        };
    }

    private static ResoniteLink.float2x2 ToModel(this Float2x2 self)
    {
        return new ResoniteLink.float2x2
        {
            m00 = self.M00,
            m01 = self.M01,
            m10 = self.M10,
            m11 = self.M11,
        };
    }

    private static Float3x3 ToProto(this ResoniteLink.float3x3 self)
    {
        return new Float3x3
        {
            M00 = self.m00,
            M01 = self.m01,
            M02 = self.m02,
            M10 = self.m10,
            M11 = self.m11,
            M12 = self.m12,
            M20 = self.m20,
            M21 = self.m21,
            M22 = self.m22,
        };
    }

    private static ResoniteLink.float3x3 ToModel(this Float3x3 self)
    {
        return new ResoniteLink.float3x3
        {
            m00 = self.M00,
            m01 = self.M01,
            m02 = self.M02,
            m10 = self.M10,
            m11 = self.M11,
            m12 = self.M12,
            m20 = self.M20,
            m21 = self.M21,
            m22 = self.M22,
        };
    }

    private static Float4x4 ToProto(this ResoniteLink.float4x4 self)
    {
        return new Float4x4
        {
            M00 = self.m00,
            M01 = self.m01,
            M02 = self.m02,
            M03 = self.m03,
            M10 = self.m10,
            M11 = self.m11,
            M12 = self.m12,
            M13 = self.m13,
            M20 = self.m20,
            M21 = self.m21,
            M22 = self.m22,
            M23 = self.m23,
            M30 = self.m30,
            M31 = self.m31,
            M32 = self.m32,
            M33 = self.m33,
        };
    }

    private static ResoniteLink.float4x4 ToModel(this Float4x4 self)
    {
        return new ResoniteLink.float4x4
        {
            m00 = self.M00,
            m01 = self.M01,
            m02 = self.M02,
            m03 = self.M03,
            m10 = self.M10,
            m11 = self.M11,
            m12 = self.M12,
            m13 = self.M13,
            m20 = self.M20,
            m21 = self.M21,
            m22 = self.M22,
            m23 = self.M23,
            m30 = self.M30,
            m31 = self.M31,
            m32 = self.M32,
            m33 = self.M33,
        };
    }

    private static Double2x2 ToProto(this ResoniteLink.double2x2 self)
    {
        return new Double2x2
        {
            M00 = self.m00,
            M01 = self.m01,
            M10 = self.m10,
            M11 = self.m11,
        };
    }

    private static ResoniteLink.double2x2 ToModel(this Double2x2 self)
    {
        return new ResoniteLink.double2x2
        {
            m00 = self.M00,
            m01 = self.M01,
            m10 = self.M10,
            m11 = self.M11,
        };
    }

    private static Double3x3 ToProto(this ResoniteLink.double3x3 self)
    {
        return new Double3x3
        {
            M00 = self.m00,
            M01 = self.m01,
            M02 = self.m02,
            M10 = self.m10,
            M11 = self.m11,
            M12 = self.m12,
            M20 = self.m20,
            M21 = self.m21,
            M22 = self.m22,
        };
    }

    private static ResoniteLink.double3x3 ToModel(this Double3x3 self)
    {
        return new ResoniteLink.double3x3
        {
            m00 = self.M00,
            m01 = self.M01,
            m02 = self.M02,
            m10 = self.M10,
            m11 = self.M11,
            m12 = self.M12,
            m20 = self.M20,
            m21 = self.M21,
            m22 = self.M22,
        };
    }

    private static Double4x4 ToProto(this ResoniteLink.double4x4 self)
    {
        return new Double4x4
        {
            M00 = self.m00,
            M01 = self.m01,
            M02 = self.m02,
            M03 = self.m03,
            M10 = self.m10,
            M11 = self.m11,
            M12 = self.m12,
            M13 = self.m13,
            M20 = self.m20,
            M21 = self.m21,
            M22 = self.m22,
            M23 = self.m23,
            M30 = self.m30,
            M31 = self.m31,
            M32 = self.m32,
            M33 = self.m33,
        };
    }

    private static ResoniteLink.double4x4 ToModel(this Double4x4 self)
    {
        return new ResoniteLink.double4x4
        {
            m00 = self.M00,
            m01 = self.M01,
            m02 = self.M02,
            m03 = self.M03,
            m10 = self.M10,
            m11 = self.M11,
            m12 = self.M12,
            m13 = self.M13,
            m20 = self.M20,
            m21 = self.M21,
            m22 = self.M22,
            m23 = self.M23,
            m30 = self.M30,
            m31 = self.M31,
            m32 = self.M32,
            m33 = self.M33,
        };
    }

}
