

// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!

namespace Rfmk.Resolink.Grpc.Bridge.Converters;

public static partial class Convert
{
    private static FloatQ ToProto(this ResoniteLink.floatQ self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.floatQ ToModel(this FloatQ self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static DoubleQ ToProto(this ResoniteLink.doubleQ self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.doubleQ ToModel(this DoubleQ self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Float2 ToProto(this ResoniteLink.float2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.float2 ToModel(this Float2 self) => new()
    {
        x = self.X,
        y = self.Y,
    };

    private static Float3 ToProto(this ResoniteLink.float3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.float3 ToModel(this Float3 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
    };

    private static Float4 ToProto(this ResoniteLink.float4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.float4 ToModel(this Float4 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Double2 ToProto(this ResoniteLink.double2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.double2 ToModel(this Double2 self) => new()
    {
        x = self.X,
        y = self.Y,
    };

    private static Double3 ToProto(this ResoniteLink.double3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.double3 ToModel(this Double3 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
    };

    private static Double4 ToProto(this ResoniteLink.double4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.double4 ToModel(this Double4 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Byte2 ToProto(this ResoniteLink.byte2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.byte2 ToModel(this Byte2 self) => new()
    {
        x = (byte)self.X,
        y = (byte)self.Y,
    };

    private static Byte3 ToProto(this ResoniteLink.byte3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.byte3 ToModel(this Byte3 self) => new()
    {
        x = (byte)self.X,
        y = (byte)self.Y,
        z = (byte)self.Z,
    };

    private static Byte4 ToProto(this ResoniteLink.byte4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.byte4 ToModel(this Byte4 self) => new()
    {
        x = (byte)self.X,
        y = (byte)self.Y,
        z = (byte)self.Z,
        w = (byte)self.W,
    };

    private static Ushort2 ToProto(this ResoniteLink.ushort2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.ushort2 ToModel(this Ushort2 self) => new()
    {
        x = (ushort)self.X,
        y = (ushort)self.Y,
    };

    private static Ushort3 ToProto(this ResoniteLink.ushort3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.ushort3 ToModel(this Ushort3 self) => new()
    {
        x = (ushort)self.X,
        y = (ushort)self.Y,
        z = (ushort)self.Z,
    };

    private static Ushort4 ToProto(this ResoniteLink.ushort4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.ushort4 ToModel(this Ushort4 self) => new()
    {
        x = (ushort)self.X,
        y = (ushort)self.Y,
        z = (ushort)self.Z,
        w = (ushort)self.W,
    };

    private static Uint2 ToProto(this ResoniteLink.uint2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.uint2 ToModel(this Uint2 self) => new()
    {
        x = self.X,
        y = self.Y,
    };

    private static Uint3 ToProto(this ResoniteLink.uint3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.uint3 ToModel(this Uint3 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
    };

    private static Uint4 ToProto(this ResoniteLink.uint4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.uint4 ToModel(this Uint4 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Ulong2 ToProto(this ResoniteLink.ulong2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.ulong2 ToModel(this Ulong2 self) => new()
    {
        x = self.X,
        y = self.Y,
    };

    private static Ulong3 ToProto(this ResoniteLink.ulong3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.ulong3 ToModel(this Ulong3 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
    };

    private static Ulong4 ToProto(this ResoniteLink.ulong4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.ulong4 ToModel(this Ulong4 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Sbyte2 ToProto(this ResoniteLink.sbyte2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.sbyte2 ToModel(this Sbyte2 self) => new()
    {
        x = (sbyte)self.X,
        y = (sbyte)self.Y,
    };

    private static Sbyte3 ToProto(this ResoniteLink.sbyte3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.sbyte3 ToModel(this Sbyte3 self) => new()
    {
        x = (sbyte)self.X,
        y = (sbyte)self.Y,
        z = (sbyte)self.Z,
    };

    private static Sbyte4 ToProto(this ResoniteLink.sbyte4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.sbyte4 ToModel(this Sbyte4 self) => new()
    {
        x = (sbyte)self.X,
        y = (sbyte)self.Y,
        z = (sbyte)self.Z,
        w = (sbyte)self.W,
    };

    private static Short2 ToProto(this ResoniteLink.short2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.short2 ToModel(this Short2 self) => new()
    {
        x = (short)self.X,
        y = (short)self.Y,
    };

    private static Short3 ToProto(this ResoniteLink.short3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.short3 ToModel(this Short3 self) => new()
    {
        x = (short)self.X,
        y = (short)self.Y,
        z = (short)self.Z,
    };

    private static Short4 ToProto(this ResoniteLink.short4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.short4 ToModel(this Short4 self) => new()
    {
        x = (short)self.X,
        y = (short)self.Y,
        z = (short)self.Z,
        w = (short)self.W,
    };

    private static Int2 ToProto(this ResoniteLink.int2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.int2 ToModel(this Int2 self) => new()
    {
        x = self.X,
        y = self.Y,
    };

    private static Int3 ToProto(this ResoniteLink.int3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.int3 ToModel(this Int3 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
    };

    private static Int4 ToProto(this ResoniteLink.int4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.int4 ToModel(this Int4 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Long2 ToProto(this ResoniteLink.long2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.long2 ToModel(this Long2 self) => new()
    {
        x = self.X,
        y = self.Y,
    };

    private static Long3 ToProto(this ResoniteLink.long3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.long3 ToModel(this Long3 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
    };

    private static Long4 ToProto(this ResoniteLink.long4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.long4 ToModel(this Long4 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Bool2 ToProto(this ResoniteLink.bool2 self) => new()
    {
        X = self.x,
        Y = self.y,
    };

    private static ResoniteLink.bool2 ToModel(this Bool2 self) => new()
    {
        x = self.X,
        y = self.Y,
    };

    private static Bool3 ToProto(this ResoniteLink.bool3 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
    };

    private static ResoniteLink.bool3 ToModel(this Bool3 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
    };

    private static Bool4 ToProto(this ResoniteLink.bool4 self) => new()
    {
        X = self.x,
        Y = self.y,
        Z = self.z,
        W = self.w,
    };

    private static ResoniteLink.bool4 ToModel(this Bool4 self) => new()
    {
        x = self.X,
        y = self.Y,
        z = self.Z,
        w = self.W,
    };

    private static Float2x2 ToProto(this ResoniteLink.float2x2 self) => new()
    {
        M00 = self.m00,
        M01 = self.m01,
        M10 = self.m10,
        M11 = self.m11,
    };

    private static ResoniteLink.float2x2 ToModel(this Float2x2 self) => new()
    {
        m00 = self.M00,
        m01 = self.M01,
        m10 = self.M10,
        m11 = self.M11,
    };
    private static Float3x3 ToProto(this ResoniteLink.float3x3 self) => new()
    {
        M00 = self.m00,
        M01 = self.m01,
        M02 = self.m02,
        M10 = self.m10,
        M11 = self.m11,
        M12 = self.m12,
        M20 = self.m20,
        M21 = self.m21,
        M22 = self.m22,
    };

    private static ResoniteLink.float3x3 ToModel(this Float3x3 self) => new()
    {
        m00 = self.M00,
        m01 = self.M01,
        m02 = self.M02,
        m10 = self.M10,
        m11 = self.M11,
        m12 = self.M12,
        m20 = self.M20,
        m21 = self.M21,
        m22 = self.M22,
    };
    private static Float4x4 ToProto(this ResoniteLink.float4x4 self) => new()
    {
        M00 = self.m00,
        M01 = self.m01,
        M02 = self.m02,
        M03 = self.m03,
        M10 = self.m10,
        M11 = self.m11,
        M12 = self.m12,
        M13 = self.m13,
        M20 = self.m20,
        M21 = self.m21,
        M22 = self.m22,
        M23 = self.m23,
        M30 = self.m30,
        M31 = self.m31,
        M32 = self.m32,
        M33 = self.m33,
    };

    private static ResoniteLink.float4x4 ToModel(this Float4x4 self) => new()
    {
        m00 = self.M00,
        m01 = self.M01,
        m02 = self.M02,
        m03 = self.M03,
        m10 = self.M10,
        m11 = self.M11,
        m12 = self.M12,
        m13 = self.M13,
        m20 = self.M20,
        m21 = self.M21,
        m22 = self.M22,
        m23 = self.M23,
        m30 = self.M30,
        m31 = self.M31,
        m32 = self.M32,
        m33 = self.M33,
    };
    private static Double2x2 ToProto(this ResoniteLink.double2x2 self) => new()
    {
        M00 = self.m00,
        M01 = self.m01,
        M10 = self.m10,
        M11 = self.m11,
    };

    private static ResoniteLink.double2x2 ToModel(this Double2x2 self) => new()
    {
        m00 = self.M00,
        m01 = self.M01,
        m10 = self.M10,
        m11 = self.M11,
    };
    private static Double3x3 ToProto(this ResoniteLink.double3x3 self) => new()
    {
        M00 = self.m00,
        M01 = self.m01,
        M02 = self.m02,
        M10 = self.m10,
        M11 = self.m11,
        M12 = self.m12,
        M20 = self.m20,
        M21 = self.m21,
        M22 = self.m22,
    };

    private static ResoniteLink.double3x3 ToModel(this Double3x3 self) => new()
    {
        m00 = self.M00,
        m01 = self.M01,
        m02 = self.M02,
        m10 = self.M10,
        m11 = self.M11,
        m12 = self.M12,
        m20 = self.M20,
        m21 = self.M21,
        m22 = self.M22,
    };
    private static Double4x4 ToProto(this ResoniteLink.double4x4 self) => new()
    {
        M00 = self.m00,
        M01 = self.m01,
        M02 = self.m02,
        M03 = self.m03,
        M10 = self.m10,
        M11 = self.m11,
        M12 = self.m12,
        M13 = self.m13,
        M20 = self.m20,
        M21 = self.m21,
        M22 = self.m22,
        M23 = self.m23,
        M30 = self.m30,
        M31 = self.m31,
        M32 = self.m32,
        M33 = self.m33,
    };

    private static ResoniteLink.double4x4 ToModel(this Double4x4 self) => new()
    {
        m00 = self.M00,
        m01 = self.M01,
        m02 = self.M02,
        m03 = self.M03,
        m10 = self.M10,
        m11 = self.M11,
        m12 = self.M12,
        m13 = self.M13,
        m20 = self.M20,
        m21 = self.M21,
        m22 = self.M22,
        m23 = self.M23,
        m30 = self.M30,
        m31 = self.M31,
        m32 = self.M32,
        m33 = self.M33,
    };
}
